language: python
python:
  - "3.6"
env:
  - DB_NAME=testdb DB_USER=postgres DB_PASSWORD= DB_HOST=localhost
install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - createdb testdb;
script:
  - python -m pytest --cov=app --cov-report=term-missing

