FORMAT: 1A
HOST: https://fastfoodfastapiv2.herokuapp.com/api/v2

# fastfoodfast

Polls is a simple API allowing consumers to view polls and vote in them.

## Menu Collections [/menu]

### List of menu items [GET]

+ Response 200 (application/json)

        [
            {
                "message": "success",
                "data": [
                    {
                        "meal_id": "1",
                        "name": "Chapati ndengu",
                        "description": "Some good chaps for the rest"
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a new menu item [POST]

You may create a menu item here if you're an admin user. It takes a JSON object
containing the name, description and the price.

+ Request (application/json)

        {
            "name": "Kuku Fry",
            "description": "Some good Kuku choma",
            "price": "200"
        }

+ Response 201 (application/json)

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
## The User Login Collection [/auth/signup]
### Login into your account [POST]
After creating an account you may want to log in and place some orders or just order some items
from the API. It takes JSON object containing
+ Response 200 (application/json)
    {
        "message": "You successfully logged in",
        "token": 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjMiLCJmdWxsbmFtZXMiOiJTaWxhcyBLZW5uZXRoIiwidXNlcm5hbWUiOiJzaWxhc2tlbm4iLCJlbWFpbCI6InNpbGFza2VubkBnbWFpbC5jb20iLCJ1c2VyX3R5cGUiOiJub3JtYWwiLCJpYXQiOjE1Mzg2ODM1NzAsImV4cCI6MTUzODY4NDQ3MH0.pXjFs5SmGPao4Y-FT_JJDb4yL3Q2btR6O8g5PCp6rnQ'
    }
## The User Sign Up Collection[/auth/signup]